### Create a new todo entity
POST http://localhost:8080/api/todos
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
  "title": "First todo",
  "description": "desc 1",
  "completed": false,
  "userId": "{{admin_user_id}}"
}

### ADMIN create todo for selected user
POST http://localhost:8080/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Admin created todo",
  "description": "created by admin",
  "completed": false,
  "userId": "{{regular_user_id}}"
}
