### GET request to get all todos
#GET http://localhost:4000/api/todos

GET http://localhost:8080/api/todos
Authorization: Bearer {{token}}

###

### USER should only see own todos
GET http://localhost:8080/api/todos
Authorization: Bearer {{user_token}}

###
