### GET request to get all todos
@id = 580972b3-881c-4061-9e29-7bc0e39f7f6e

GET http://localhost:8080/api/todos/{{id}}
Authorization: Bearer {{user_token}}

###

GET http://localhost:8080/api/todos/{{id}}
Authorization: Bearer {{token}}

###

### Ownership check (should be 403 when todo belongs to another user)
GET http://localhost:8080/api/todos/{{id}}
Authorization: Bearer {{user_token}}

###
