### Update todo
@id = 69812e22-7f89-4f3e-bf89-e464de8ea5da

PUT http://localhost:8080/api/todos/{{id}}
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
  "title": "Updated todo title",
  "description": "updated desc",
  "completed": false
}
