### Register request to create user
POST http://localhost:4002/register
Content-Type: application/json

{
  "username": "admin_user",
  "email": "admin_user@example.com",
  "password": "password"
}

###

POST http://localhost:4002/register
Content-Type: application/json

{
  "username": "regular_user_2",
  "email": "regular_user_2@example.com",
  "password": "Password1!"
}